### ISSUE TITLE
Multiscreen

### ISSUE THREAD

**Issue by jwagsters** [tonyfederer/EasyVideoScreensaver#3]
It there any way to get this to play on two screens?  Either duplicated or across both?

**Comment by HannibalZA** [comment]
App.xaml.cs line 65
![image](https://user-images.githubusercontent.com/2007626/224238404-fb5f2ae9-a4e9-468d-950e-905150f22f0a.png)

Duplicated, not spanned.

**Comment by tonyfederer** [comment]
I added the ability to play the video on all monitors.
