### ISSUE TITLE
Do not work on more than 1 monitor

### ISSUE THREAD

**Issue by TechieWasp** [tonyfederer/EasyVideoScreensaver#5]
I have 2 monitors. It just plays on one monitor. Could you please add support for multi monitor setup?

**Comment by HannibalZA** [comment]
App.xaml.cs, line 65

![image](https://user-images.githubusercontent.com/2007626/224238055-133b07b8-6d98-457f-b993-65fe65b130db.png)

**Comment by TechieWasp** [comment]
Thank you.

**Comment by tonyfederer** [comment]
I added the ability to play the video on all monitors.

**Comment by aforazad** [comment]
> I added the ability to play the video on all monitors.

Thank you so much.
